site_name: Guide Ops : Transition vers le Quantique
site_author: Julien Bombled
copyright: Copyright &copy; 2025 Julien Bombled - Apache 2.0 License

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Accueil: index.md
  - Labs:
    - 1. Hello World (Ping): labs/hello_world.md
  - Glossaire: glossaire.md
  - Infrastructure:
    - Architecture Ref: infra/architecture.md
    - Terraform: infra/terraform.md
  - 3. Sécurité Post-Quantique: securite.md
